version: "3.3"

services:
    server:
        build: ./server
        ports:
            - 3000:3000
        links:
        - db        


    db:
        build: ./db
        ports:
            - 5432:5432    
        environment:
            POSTGRES_DB: storyverse
            POSTGRES_USER: ${POSTGRES_USER:?err}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
            PGDATA: ./db/var/lib/postgresql/data
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d  


    # TODO
    web:
        build: ./web   